### ISSUE TITLE
Typo in image

### ISSUE THREAD

**Issue by enthus1ast** [treeform/pixiebook#2]
https://github.com/treeform/pixiebook/blob/master/text.md
https://github.com/treeform/pixiebook/raw/master/images/textSpans.png

Is: "Pixie is easy and compex."
Should be: "Pixie is easy and comp**l**ex."

**Comment by treeform** [comment]
Thank you fixed!

https://github.com/treeform/pixiebook/commit/9f9b40d7c4db6da1f2f104f4804b280e8e262176
